# Generated by Django 5.1.4 on 2024-12-25 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("train_station", "0003_remove_route_distance"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journey",
            options={"ordering": ["-departure_time"]},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="train",
            options={"ordering": ["name"]},
        ),
        migrations.AlterUniqueTogether(
            name="route",
            unique_together={("source", "destination")},
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("cargo", "seat", "journey")},
        ),
    ]
