# Generated by Django 5.1.4 on 2024-12-26 00:45

import train_station.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("train_station", "0004_alter_journey_options_alter_order_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crew",
            name="image",
            field=models.ImageField(
                null=True, upload_to=train_station.models.crew_image_file_path
            ),
        ),
    ]
